spring.application.name: api-provider

# Helps testing, should not be used in production
server.error.include-message: always

spring.threads.virtual.enabled: true

server.port: 7001

logging.level:
  root: INFO
  se.magnus: DEBUG