spring.application.name: api-provider

# Helps testing, should not be used in production
server.error.include-message: always

spring.threads.virtual.enabled: true

server.port: 7001

management:
  opentelemetry.tracing.export.otlp.endpoint: http://localhost:4318/v1/traces

  tracing.sampling.probability: 1.0

logging.level:
  root: INFO
  se.magnus: DEBUG